### ISSUE TITLE
Documentation - statement of need

### ISSUE THREAD

**Issue by andrewfowlie** [ejhigson/dyPolyChord#1]
Hi there,

For my [review](https://github.com/openjournals/joss-reviews/issues/965),

> ### Documentation
> 
> - [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

I couldn't see this information clearly in the [docs](https://dypolychord.readthedocs.io/en/latest/index.html). It was clear in the software paper, though.

**Comment by ejhigson** [comment]
Again thanks for pointing this out! I have added this bit of the paper to the software documentation at https://dypolychord.readthedocs.io/en/latest/.

If you are happy with this I will close the issue.

**Comment by andrewfowlie** [comment]
I think the docs are still missing 

> who the target audience is?

and it could be much clearer about what it calculates, i.e. the Bayesian evidence. I think both should be in the first few (if not the first) paragraph of the docs.

**Comment by ejhigson** [comment]
This is a good point - now looking at it again you are definitely right. I have added a sentence saying what nested sampling calculates as the first sentence of the homepage here https://dypolychord.readthedocs.io/en/latest/.

I am going to provisionally close this issue but let me know if you think it should be reopened!

**Comment by ejhigson** [comment]
I should add: I think it is implicit that the target audience is "people who want to calculate Bayesian evidences and/or posterior samples from a likelihood and prior", but let me know if you think this should be further clarified.
